emsdjango/urls.py
from django.contrib import admin
from django.urls import path
from ems import views

urlpatterns = [
     path('emp', views.emp),
    path('', views.emp),
    path('show', views.show),
    path('edit/<int:id>', views.edit),
    path('update/<int:id>', views.update),
    path('delete/<int:id>', views.delete),
]

ems/models.py
from django.db import models

class Employee(models.Model):
    eid = models.CharField(max_length=20)
    ename = models.CharField(max_length=100)
    eemail =  models.EmailField()
    econtact = models.CharField(max_length=15)
    class Meta:
        db_table = "employee"

ems/forms.py
from django import forms
from ems.models import Employee

class EmployeeForm(forms.ModelForm):
    
    class Meta:
        model = Employee
        fields = "__all__"

ems/views.py
from django.shortcuts import render, redirect
from ems.forms import EmployeeForm
from ems.models import Employee
def emp(request):
    if request.method == "POST":
        form = EmployeeForm(request.POST)
        if form.is_valid():
            try:
                form.save()
                return redirect()
            except:
                pass
    else:
        form = EmployeeForm()
    return render(request, "index.html", {'form':form})
def show(request):
    employees = Employee.objects.all()
    return render(request, "show.html", {'employees':employees})

def edit(request,id):
    employee = Employee.objects.get(id = id)
    return render(request, "edit.html", {'employee':employee})

def update(request,id):
    employee = Employee.objects.get(id = id)
    form = EmployeeForm(request.POST, instance= employee)
    if form.is_valid():
            form.save()
            return redirect('/show')
    return render(request, "edit.html", {'employee':employee})

def delete(request,id):
    employee = Employee.objects.get(id = id)
    employee.delete()
    return redirect('/show')
# Create your views here.

ems/templates/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>EmsUpdate</title>
  <meta charset="utf-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  {% load static %}
  <link rel="stylesheet" href={% static 'css/style.css' %}>
</head>
<body>

<a href="/emp"><h1 class = "text-center mt-3 position-logo"><span class = "text-danger"><b>E</b></span><span class = "text-primary"><i>MS</i></span></h1></a>
    <div class = "container">
    <div class = "page-title pt-5 pb-5 mb-4">Update The Info</div>
    <div class = "d-flex justify-content-center">
    <form method = "POST" class = "post-form update-form-style pl-5 pt-5 pb-3 w-75" action="/update/{{employee.id}}">
    {% csrf_token %}
        <div class="form-group row">
          <label class = "col-md-3">Employee Id:</label>
          <div class = "col-md-7">
                <input type="text" name="eid" id="id_eid" required maxlength="20" value="{{employee.eid}}" class = "w-100"/>
          </div>
        </div>

        <div class="form-group row">
          <label class = "col-md-3">Employee Name:</label>
          <div class = "col-md-7">
                <input type="text" name="ename" id="id_ename" required maxlength="100" value="{{employee.ename}}" class = "w-100"/>
          </div>
        </div>

        <div class="form-group row">
          <label class = "col-md-3">Employee Email:</label>
          <div class = "col-md-7">
                <input type="text" name="eemail" id="id_eemail" required maxlength="254" value="{{employee.eemail}}" class = "w-100"/>
          </div>
        </div>

        <div class="form-group row">
          <label class = "col-md-3">Employee Contact:</label>
          <div class = "col-md-7">
                <input type="text" name="econtact" id="id_econtact" required maxlength="15" value="{{employee.econtact}}" class = "w-100"/>
          </div>
        </div>

        <div class="form-group row">
          <label class = "col-md-3"></label>
          <div class = "col-md-7">
            <button type="submit" class="btn btn-primary">Update</button>
          </div>
        </div>

    </form>
    </div>
    <footer class = "footer-style mt-4 text-center w-100 pt-2">
<p><b>Developed By: Rupayan Debnath</b></p>
</footer>
    </div>
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>

ems/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Ems</title>
  <meta charset="utf-8">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  {% load static %}
  <link rel="stylesheet" href={% static 'css/style.css' %}>
</head>
<body>
<h1 class = "text-center mt-3">Welcome to <span class = "text-danger"><b>E</b></span><span class = "text-primary"><i>MS</i></span></h1>
<h2 class = "text-center">An Employee Management System</h2>
<div class = "text-center">
  <img src={% static 'image/header.jpg' %} class = "img-fluid image">
</div>
    <div class = "container mb-5">
    <div class = "row">
    <div class = "col-md-6 col-xs-12">
        <div class = "form-style text-center pb-3 pt-3"> 
        <form method = "POST" class = "post-form" action="/emp">
    {% csrf_token %}
            <h3 class = "mt-3 mb-5 text-primary">Add An Employee</h3>
       
        <div class="form-group row ml-5 mr-1">
          <label class = "col-md-4 col-form-label">Employee Id:</label>
          <div class = "col-md-8">
           {{form.eid}}
          </div>
        </div>

         <div class="form-group row ml-5 mr-1">
          <label class = "col-md-4 col-form-label">Employee Name:</label>
          <div class = "col-md-8">
           {{form.ename}}
          </div>
        </div>

        <div class="form-group row ml-5 mr-1">
          <label class = "col-md-4 col-form-label">Employee Email:</label>
          <div class = "col-md-8">
           {{form.eemail}}
          </div>
        </div>

        <div class="form-group row ml-5 mr-1">
          <label class = "col-md-4 col-form-label">Employee Contact:</label>
          <div class = "col-md-8">
           {{form.econtact}}
          </div>
        </div>
          <div class = "text-center">
            <button type="submit" class="btn btn-primary mb-3">Submit</button>
          </div>
        
    </form>
    </div>
    </div>
    <div class = "col-md-6 col-xs-12">
    <div class = "view-style pl-5 pr-5 pt-4">
    <h1 class = "text-center"> <span class = "text-danger"><b>E</b></span><span class = "text-primary"><i>MS</i></span></h1>
        <p class = "pt-5"><span class = "text-danger"><b>E</b></span><span class = "text-primary"><i>MS</i></span> is an Employee Management System. It is is a platform where all basic and important personal details of an employee is stored and managed. By using this system, user can manage the information of employees in an easier and quicker way.</p>
    <div class = "view pt-3 pb-3 text-center"><a href = "/show">Click Here </br>To View The Employee List</a><div>
    </div>
    </div>
    </div>
    </div>


<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>

ems/templates/show.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>EmsList</title>
  <meta charset="utf-8">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  

  {% load static %}
  <link rel="stylesheet" href={% static 'css/style.css' %}>
</head>
<body>
<a href="/emp"><h1 class = "text-center mt-3 position-logo"><span class = "text-danger"><b>E</b></span><span class = "text-primary"><i>MS</i></span></h1></a>
    <div class = "container">
    <div class = "page-title pt-5 pb-5 mb-4">Employee List</div>
        <div class = "table-responsive">
    <table class="table">
        <thead class="">
            <tr>
                <th>Employee ID</th>
                <th>Employee Name</th>
                <th>Employee Contact</th>
                <th>Employee Email</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
        {% for employee in employees%}
            <tr>
                <td>{{employee.eid}}</td>
                <td>{{employee.ename}}</td>
                <td>{{employee.eemail}}</td>
                <td>{{employee.econtact}}</td>
                <td>
                    <a href="/edit/{{employee.id}}">
                        <span class="glyphicon glyphicon-pencil"><i class="fa fa-pencil text-success" aria-hidden="true"></i>
</span>
                    </a>
                    <a href="/delete/{{employee.id}}"><i class="fa fa-trash text-danger ml-5" aria-hidden="true"></i></a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    </div>
    </div>

    <center><a href="/emp" class="btn btn-primary">Add New Record</a></center>

<div class = "container"><footer class = "footer-style mt-4 text-center w-100 pt-2 pb-2">
<p><b>Developed By: Rupayan Debnath</b></p>
</footer></div>
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>